eureka:
  client: 
    register-with-eureka: true 
    fetch-registry: true 
    service-url:
      defaultZone: ${eureka_servers:http://localhost:8761/eureka}


spring:
  cloud: 
    gateway:
      default-filters:
      - name: GlobalFilter
        args:
          baseMessage: Spring Cloud Gateway GlobalFilter
          preLogger: true
          postLogger: true
      routes:
        - id: webserver #webserver.spirng-cloud.svc.cluster.local:port
          uri: http://webserver
          predicates:
          - Path=/webserver/**
          filters:
          - name: GlobalFilter
            args:
              baseMessage: Spring Cloud Gateway GlobalFilter
              preLogger: true
              postLogger: true
          - name: RewritePath
            args:
              regexp: /webserver/
              replacement: /
      


    rabbitmq:
      host: ${mq_host:localhost}
      port: ${mq_port:5672}
      username: ${mq_id:guest}
      password: ${mq_pw:guest}
      
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true